spring:
  social:
    facebook:
      app-id: changeit
      app-secret: changeit

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: basic
      auto-approve-scopes: basic
      authorized-grant-types: authorization_code, password
      access-token-validity-seconds: 600
      refresh-token-validity-seconds: -1
